[package]
name = "modbus_register_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = {version = "0.7.4"}
diesel = {version = "2.1.4", features= ["sqlite", "returning_clauses_for_sqlite_3_35"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
tokio = { version = "1.0", features = ["full"] }

tracing-subscriber = "0.3.18"
libsqlite3-sys = { version = "0.27.0", features = ["bundled"] }
dotenvy = "0.15.7"
strum_macros = "0.26.1"
serde_with = "3.6.0"


[profile.release]
strip = true
opt-level = "z"
lto = true
panic = "abort"
