[package]
name = "t3_webview_api"
version = "0.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "t3_webview_api"
crate-type = ["cdylib", "rlib"]

[dependencies]
axum = { version = "0.7.4" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
tokio = { version = "1.0", features = ["full"] }

tracing-subscriber = "0.3.18"
strum_macros = "0.26.1"
serde_with = "3.6.1"
tower-http = { version = "0.5.1", features = ["cors", "fs"] }
dotenvy = "0.15.7"
lazy_static = "1.4.0"
open = "5.1.2"
chrono = "0.4.37"

migration = { path = "migration", version = "0.1.0" }

[dependencies.sea-orm]
version = "1.0.0-rc.3"
features = [
  "runtime-tokio",
  # "sqlx-postgres",
  # "sqlx-mysql",
  "sqlx-sqlite",
]

[dev-dependencies]
tower = { version = "0.4", features = ["util"] }

[profile.release]
strip = true
opt-level = "z"
lto = true
panic = "abort"
