name: Build & upload artifacts
on: workflow_dispatch
jobs:
  tag:
    name: Build & upload artifacts
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: |
          npm install
          npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: webview-ui
          path: dist/spa/*
